<?php
require('koneksi.php');

$result= mysqli_query($conn, "SELECT * FROM Service_form");

$service_form = [];

while ($row = mysqli_fetch_assoc($result)) {
    $service_form[]=$row;
}
?>
<!DOCTYPE html>

<html>
    <head>
        <title>Website Logistik Asikk</title>
        <link rel="icon" href="Gambar/Pesawat.png"/>
        <link rel="stylesheet" href="Index.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Muhammad Luthfi Nur Ramadhan">
        <script src="index.js"></script>
    </head>

    <body>
        <nav> 
            <div class="Introduce">
                <a href="Index1.html">
                    <h1><img src="Gambar/Pesawat.png" alt="" >Logistik Asikk</h1>
                </a>
            </div>
            <ul>
                <li>
                    <a href="Index1.html">Home</a>
                </li>
                <li>
                    <a href="About.html">About</a>
                </li>
                <li id="service">
                    <a href="service.php">Services</a>
                </li>
                <li>
                    <a href="logout.php">Log Out</a>
                </li>
                <li><img src="gambar/moon1.png" id="icon" width="15px" ?>
                </li>
            </ul>
            <div class="tentang">
                <p>Sebuah perusahaan logistik yang berdiri sejak tahun 2032.<br>Menjadi perusahaan unicorn pada tahun pertamanya.<br> Logistik asik menawarkan berbagai macamlayanan mulai dari :
                </p><br>  
        <div class="content">
            <div class="baris1"> <img src="Gambar/1.png" alt="" ><br>Sea Frieght
            <div>Sea Fright merupakan layanan pengiriman<br> jalur Laut</div></div>
            <div class="baris1"> <img src="Gambar/2.png" alt=""><br>Land Transportation
            <div>Land Transportation merupakan layanan pengiriman<br> menggunakan jalur Darat</div></div>
            <div class="baris1"> <img src="Gambar/3.png" alt=""><br>Air Frieght
            <div>Air Fright merupakan layanan pengiriman <br> menggunakan Jalur Udara</div></div>     
        </div>
            </div>
            <input class="search" type="text" name="text" placeholder="trace & track" autocomplete="off">
            <input class="button" type="submit" name="submit" value="Search">
        </nav>

        <footer>
            Copyright &copy; 2022
            Designed by Rama 
            <div class="contact"> 
                <a href="https://wa.me/08978284996">
                    Contact us
                </a>
            </div>
        </footer>

        <script src="index.js"></script>

    </body>
</html>